### PR TITLE
Oracle Integration 3 - Cookbook - ERP Cloud Real Time Synchronization

### PR DESCRIPTION
**Pull request by isubhani006**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Please resolve merge conflicts on your branch. You can refer to this guide’s Troubleshooting https://github.com/oracle-livelabs/oic/pull/3 for help: https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest#Appendix:TroubleshootingTips

**Comment by isubhani006** [comment]
Hi,
Is there any action for me?

Regards,
Subhani


From: Arabella Yao ***@***.***>
Date: Tuesday, 20 September 2022 at 22:31
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] Oracle Integration 3 - Cookbook - ERP Cloud Real Time Synchronization (PR #9)

@arabellayao requested changes on this pull request.

Please resolve merge conflicts on your branch. You can refer to this guide’s Troubleshooting #3<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/oic/pull/3__;!!ACWV5N9M2RV99hQ!KNQld1BLYkSkr5JcvBL5jW00Q7JV-9dg4GnNHw7o99I8m9B2WhhqykX1nkSPtXV9F-vkku37byHDboMYXq6grWRBODmzbS8$> for help: https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest#Appendix:TroubleshootingTips<https://urldefense.com/v3/__https:/oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest*Appendix:TroubleshootingTips__;Iw!!ACWV5N9M2RV99hQ!KNQld1BLYkSkr5JcvBL5jW00Q7JV-9dg4GnNHw7o99I8m9B2WhhqykX1nkSPtXV9F-vkku37byHDboMYXq6grWRBspILfww$>

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved 
Conflicting files
oic-gen3/cookbooks/erp-cloud/realtimesync/workshops/tenancy/manifest.json

**Comment by isubhani006** [comment]
Yes, I have modified the file. So, what should I do?
I would appreciate if you can help me on this.

Regards,
Subhani

From: Madhusudhan Rao ***@***.***>
Date: Wednesday, 21 September 2022 at 09:44
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] Oracle Integration 3 - Cookbook - ERP Cloud Real Time Synchronization (PR #9)

This branch has conflicts that must be resolved
Conflicting files
oic-gen3/cookbooks/erp-cloud/realtimesync/workshops/tenancy/manifest.json

**Comment by isubhani006** [comment]
It is my livelab file and no one modified it. We need to take the new file only

Regards,
Subhani


From: Subhani Sahib Italapuram ***@***.***>
Date: Wednesday, 21 September 2022 at 09:46
To: oracle-livelabs/oic ***@***.***>, oracle-livelabs/oic ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [External] : Re: [oracle-livelabs/oic] Oracle Integration 3 - Cookbook - ERP Cloud Real Time Synchronization (PR #9)
Yes, I have modified the file. So, what should I do?
I would appreciate if you can help me on this.

Regards,
Subhani

From: Madhusudhan Rao ***@***.***>
Date: Wednesday, 21 September 2022 at 09:44
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] Oracle Integration 3 - Cookbook - ERP Cloud Real Time Synchronization (PR #9)

This branch has conflicts that must be resolved
Conflicting files
oic-gen3/cookbooks/erp-cloud/realtimesync/workshops/tenancy/manifest.json

**Comment by madhusudhanrao-ppm** [comment]
check the troubleshooting tips in this guide

https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Comment by isubhani006** [comment]
Thank you Madhu. Your document helped me.

Regards,
Subhani

From: Madhusudhan Rao ***@***.***>
Date: Wednesday, 21 September 2022 at 10:24
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] Oracle Integration 3 - Cookbook - ERP Cloud Real Time Synchronization (PR #9)

Merged #9<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/oic/pull/9__;!!ACWV5N9M2RV99hQ!KETw8ib2zlRhdasLmBfLmc90_SwNh6SIiaYghSz5hsRs7AUWn79zQ0rorVaEe69pnJ1iDh193QbVpZnOgZBrIGycrccSt-c$> into main.

**Comment by isubhani006** [comment]
Thank you. Could you please check now.

Regards,
Subhani

From: Madhusudhan Rao ***@***.***>
Date: Wednesday, 21 September 2022 at 09:49
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] Oracle Integration 3 - Cookbook - ERP Cloud Real Time Synchronization (PR #9)

check the troubleshooting tips in this guide

https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest<https://urldefense.com/v3/__https:/oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest__;!!ACWV5N9M2RV99hQ!L23dmqgsxiR7Mi0yjPk_a2yDw2jxgOKwo5P_zcTNxpfx3zEFN7UnKi7xFKoixiqYBMiaGvSUQmpoLBTFm8vjSHcPmg4NpqQ$>

**Pull request merged**
