### PR TITLE
OIC B2B Getting Started

### PR DESCRIPTION
**Pull request by isubhani006**
# 11614 and minor changes in 11275 and 11321

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ y] All filenames are lower case (including folders, images, files, etc.)
- [ y] Filenames are descriptive
- [ y] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ y] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ y] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by carmenberdant1 — CHANGES_REQUESTED** [review]
Hi @isubhani006, please make sure that all your images/files are lowercase. Thank you

**Comment by isubhani006** [comment]
Am sorry, missed it. I have changed all the file names to lowercase and made corresponding changes.

Thanks & Regards,
Subhani

From: Carmen Berdant ***@***.***>
Sent: 27 March 2024 13:44
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] OIC B2B Getting Started (PR #52)


@carmenberdant1 requested changes on this pull request.

Hi @isubhani006<https://urldefense.com/v3/__https:/github.com/isubhani006__;!!ACWV5N9M2RV99hQ!KWmHiNkpdklu8CVHE4T5riA5LR90KPXjS-V-llR_5e8oN2Cm4nNbhjieBIbAK-32IS-sKvekr7N8iFyeZ-KGFDadkD1nrjc$>, please make sure that all your images/files are lowercase. Thank you

**Comment by isubhani006** [comment]
Thank you. This is done.

Regards,
Subhani


From: Dan Wiliams ***@***.***>
Sent: 27 March 2024 16:57
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] OIC B2B Getting Started (PR #52)


@dannymgithub requested changes on this pull request.

@isubhani006<https://urldefense.com/v3/__https:/github.com/isubhani006__;!!ACWV5N9M2RV99hQ!IRpMvqBIZXiXFh8NLXtUDz3emVMliWjq4IqR-p3Uo8M9djkeDnR7kbYFVrOZ2-2oyaKWAasu89RjnPHd8QZtTTRsgJzmEoo$> please make change so we can move forward.

________________________________

In oic-gen3/core-competencies/b2b/getting-started/workshops/tenancy/manifest.json<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/oic/pull/52*discussion_r1540924352__;Iw!!ACWV5N9M2RV99hQ!IRpMvqBIZXiXFh8NLXtUDz3emVMliWjq4IqR-p3Uo8M9djkeDnR7kbYFVrOZ2-2oyaKWAasu89RjnPHd8QZtTTRsam0-im4$>:

> +        },

+        {

+            "title": "Lab 1: Provision Oracle Integration 3",

+            "filename": "../../../../../common/provision-oic/provision.md"

+        },

+        {

+            "title": "Lab 2: Enable File Server",

+            "filename": "../../../../../common/enable-file-server/enable-file-server.md"

+        },

+        {

+            "title": "Lab 3: Setup",

+            "filename": "../../setup/setup.md"

+        },

+        {

+            "title": "Lab 4: B2B Concepts",

+            "filename": "../../getting-started-b2b/gettingStartedB2B.md"

please change file path from gettingStartedB2B.md to gettingstartedb2b.md, as that is the name of your file. Without this fix, this will cause lab4 not not be visible.

**Review by dannymgithub — APPROVED** [review]

**Review by dannymgithub — APPROVED** [review]

**Comment by isubhani006** [comment]
Thank you.


From: Dan Wiliams ***@***.***>
Sent: 27 March 2024 18:30
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] OIC B2B Getting Started (PR #52)


Merged #52<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/oic/pull/52__;!!ACWV5N9M2RV99hQ!PFT6PhtqXVcBw6Gz0ot88WXlQt1QX-UJDcavdUkhrwDCwLqWDt-y_--08Y3K-57FJba0XAH7HqNVcRV3NaWqRiEwpepjzec$> into main.

**Pull request merged**
