### PR TITLE
WMS ID: 11705 - Get Started with Robots in Oracle Integration 3

### PR DESCRIPTION
**Pull request by chablani**
WMS ID: 11705

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by carmenberdant1 — APPROVED** [review]

**Comment by carmenberdant1** [comment]
HI @chablani please resolve your conflicts. Thank you!

**Comment by chablani** [comment]
I removed the <br> tags from the MD files. What's wrong with the images?

**Comment by hope-fisher** [comment]
Hi @chablani, looks like there are still conflicts preventing this from being able to merge. This can happen if a branch was out of sync when the PR was created. Try to resolve these conflicts but you may need additional troubleshooting. Happy to connect to walkthrough. 

Screenshot 2024-08-09 at 1 23 14 PM

**Comment by chablani** [comment]
Yes, could we have a zoom?

**Comment by hope-fisher** [comment]
will create new PR.

**Pull request closed without merging**
